# Generated by Django 4.2 on 2025-05-24 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_dese',
            new_name='item_desc',
        ),
    ]
