# Generated by Django 4.2 on 2025-06-04 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_remove_item_item_imaage_item_item_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.ImageField(default='images/pl.png', upload_to='images/'),
        ),
    ]
